# Generated by Django 3.1.6 on 2021-07-03 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='favorites',
        ),
    ]
